uavcan_node_id:           42
uavcan_node_name:         "hitl.baro"
bridges:                  ["BaroStaticPressureRosToUavcan",     "/uav/static_pressure",
                           "BaroStaticTemperatureRosToUavcan",  "/uav/static_temperature",
]
