uavcan_node_id:           46
uavcan_node_name:         "inno.sensors"
bridges:                  ["DiffPressureRosToUavcan",           "/uav/raw_air_data",
                           "ImuRosToUavcan",                    "/uav/imu",

                           "EscStatusRosToUavcan",              "/uav/esc_status",
                           "IceReciprocatingStatusRosToUavcan", "/uav/ice_status",
                           "IceFuelTankStatusRosToUavcan",      "/uav/fuel_tank",
                           "BatteryInfoRosToUavcan",            "/uav/battery"
]
